language: java
before_install:
- sudo curl -sL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.21.0/docker-compose-"$(uname -s)"-"$(uname -m)"
- sudo chmod    +x /usr/local/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- docker build --build-arg JAR_FILE=/target/backend.jar -t 592115518/234project-backend  .
- docker push 592115518/234project-backend
script:
- docker-compose -H "$DOCKER_HOST" up -d
