language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t lyw1024/se234-lab11-backend:latest  .
- docker push lyw1024/se234-lab11-backend:latest
- docker pull "dto80/project234-frontend:latest
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: ZunPzsbis8B+Y0d5iIC9lPOWa6vAcms8liW+B8NiKDyJXI/jz8lcYEW4aTDYZpokb3YRYhQ3DZ/JvOrBFPSml6xxbzGx+aMlujoGuicvksnXLOht+y/Vs5EyDSZdr8RpI7rTF4wziu0yH/Hw8bKucaGxxkbcVLob4PxG9vpSATdI4/pNOFOm2fH4KdSfifFKaQaWzn8wG+0REDsT5b0C7N701G+sYxqZY0WGW5SrFGb4v/DHWLl4JBMmTP+CYn3vgo/wFdyLwiVlouDGcbQs1QR+kKHQWsh0Xojib5dwfiQqvYmFKDM8stL1mdpm1wa7gGy3MlepwYbuPN2RQFm/xoZoWEzIltvaU6JegDrWjy+XCSpFqN0cAvQSgKRq2gqFzR+X53gTNnTkwOdyIbq7XbIWSSoU26vhbqgdILg5/HyZq6DRtb6/p4lAETipdQnKPMwttYsptr1OFEGeIXsFB/b944IB6K4aUOsmkecSIWruTwXgG34u1f7rsmwG0cZ+672sHMLk3UG8GI0FiaXaIvEDaG8J2llnM9OfvzdNq0EArRPagHf01N9V6ACvG76U9BcXRkrIE7OntchxskTdVp+PJZKF271f81StduHJMpuwr7hZlM9EYlH/KPvH1wx1U3Pxv8MojXsY1Y8rCBWTkWirQXsph+0J/8L5SsYpfSA=
  - secure: YhdnZ4xlMPwzBi7iLmugOGx4HqgTKYulzXInsJBJa8SxE+oeCbC1wL9709DaGRdARM4YjsIP0pOArfvjTJ2WEJhOdsNUtS9xxkRqWev4KvncSxi0/JJ5KDljxLsFbJDqPcGUTLFV5bh8S1inoUNaUbK41QQ4JWakuFOgG/NwwhZYQymmnXLr3Gor6hzn+bzDAUCwAQ3WH13v3BcgVVejNCmByQiUsj3fmv9F/VDV4YEPpZppkWvU9b/kNr2R5yDhqvc4rOkWWk/wZ4/ve/561Zns4RQIJbCZ2lLyZmzev6LuWbcGHj4CvsDmTgc7hVIFpubRAFosTlkmXAZdsrtick60h/3LPU73L0gurGn3gYWB+Qay+StQKmzWVUJel4VDUoITqldBRFCNn2gKpXrjCkScTlQy96uvM2ZoQkfb8Q8BjyZk6DcYMwbRyggADa1ad7EsLgGCuNZ6mesmfa/JLkkfs6HxzyOKHGQcPuRmagZqSWqgYYOSMXWpr7hAJ+U+qdiETTPzQJMduTcIYa0HZS31rKvX/ydYpI49IzRHMD63WHjMGw248wrCdXfVzcaQ/BdMzWds7Ha6WW9rcxq0dRwHo177MSVzhgo73Xjpmv08zQ1ho4SEUb3AN/fI1SjsZew56me+CEcRKFqdhb5iyLjChMsFJvNPs58t4zJQizw=
  - secure: pY0XffRxOzatrkH9wBCqv7+J/jGfRfFwYNbNaLUD9XyUY0Bz9ZMnf26gDJvmLeHPud2w37iU5L1Oxsz6zboJaX+K6r+g5HwKKZgtnjb+bLXSCinZdwpeMhrv1Ux4SlCd/I9ReJ7FauWt7Yq3H8EqkuBoF2oFJ5RcuqP+bgzeyXRiZBpfaidu0GYgpUA1mjh7r7hfOJV/5cnX/tG17JYtAOXaT+GY+SD5iFMJNnBFq/kSH92K5DfUskSsoXdPkYnyiVKmJsfQ/oHUDtlfS4zXBUQcxnnQ/jbOG+u6bCvUDEQGlNhea8GoNSz3MC1C9e0tp2YjyHBoDVXOaoSopyp2D6JB8uMzN/7Q5eRTO9jlwH69NST7gbuh77+8WQYPgmFnQ0/cqW0YFmN9AfCFYR5XU5AEQTvI/KNE88JPZjyu677/PEPuABw4YFIzgKzQIqmCRdBj92kz8ogMtyAQb8wqE/Tbb28CWtitum6+qoTP/RQMPvcBnUvYId1VWop1ZOP323mthVD7DhHRFTZIgR4eXx8KImfvRXVFR10XGMTOm5Y+87/Y/2qhQd6j1yQLvVLCf9qAL/lQmr0GLBR0BSyRHX+hw0PXkz1Wn87bGJUx2P6emDG4Il2LT9bLsaoUfM7YUHyuwmo10MtgR+NEax8rmSvD0nqHB8glauzCFteSXcM=
